table DadosMarketing
	lineageTag: e53a1b4c-28b5-4271-b737-4cee0e43049c

	measure TotalGasto = SUMX(DadosMarketing, DadosMarketing[Gasto com Alimentos] + DadosMarketing[Gasto com Brinquedos] + DadosMarketing[Gasto com Eletronicos] + DadosMarketing[Gasto com Moveis] + DadosMarketing[Gasto com Utilidades] + DadosMarketing[Gasto com Vestuario])
		formatString: 0
		lineageTag: df83105b-54e8-4f3a-be9a-aef28d1a9869

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 599e4e44-175b-4f7d-81a8-4937fa42bb41
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Ano Nascimento'
		dataType: int64
		formatString: 0
		lineageTag: 5b52d321-33ad-4d83-b63e-cd813d7734ee
		summarizeBy: sum
		sourceColumn: Ano Nascimento

		annotation SummarizationSetBy = Automatic

	column Escolaridade
		dataType: string
		lineageTag: 889c0907-72f4-4f89-9422-3861ca64fdff
		summarizeBy: none
		sourceColumn: Escolaridade

		annotation SummarizationSetBy = Automatic

	column 'Estado Civil'
		dataType: string
		lineageTag: 9c2f03cb-cdf4-42d1-a651-49a103c7e6ba
		summarizeBy: none
		sourceColumn: Estado Civil

		annotation SummarizationSetBy = Automatic

	column 'Salario Anual'
		dataType: int64
		formatString: 0
		lineageTag: 5c9b1e32-014d-4f2c-836c-c334ddfdbc59
		summarizeBy: sum
		sourceColumn: Salario Anual

		annotation SummarizationSetBy = Automatic

	column 'Filhos em Casa'
		dataType: int64
		formatString: 0
		lineageTag: aa8f31ec-596b-405c-8d3e-c44d961288a5
		summarizeBy: sum
		sourceColumn: Filhos em Casa

		annotation SummarizationSetBy = Automatic

	column 'Adolescentes em Casa'
		dataType: int64
		formatString: 0
		lineageTag: bfb9d008-25d9-4e67-9e3e-91e3bd622443
		summarizeBy: sum
		sourceColumn: Adolescentes em Casa

		annotation SummarizationSetBy = Automatic

	column 'Data Cadastro'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a5349dd6-5f71-447a-b111-ecb3156e3d31
		summarizeBy: none
		sourceColumn: Data Cadastro

		variation Variation
			isDefault
			relationship: 07be08c6-4ad7-4433-86e2-55793fc3f386
			defaultHierarchy: LocalDateTable_a8c13822-9bd9-4fc7-8ccc-6fca296dafc3.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Dias Desde Ultima Compra'
		dataType: int64
		formatString: 0
		lineageTag: 372db38f-f076-4ec8-86f0-0b97a7ab7b80
		summarizeBy: sum
		sourceColumn: Dias Desde Ultima Compra

		annotation SummarizationSetBy = Automatic

	column 'Gasto com Eletronicos'
		dataType: int64
		formatString: 0
		lineageTag: cb09da03-6914-4b55-a305-9647314cb7b0
		summarizeBy: sum
		sourceColumn: Gasto com Eletronicos

		annotation SummarizationSetBy = Automatic

	column 'Gasto com Brinquedos'
		dataType: int64
		formatString: 0
		lineageTag: 7af42fc0-9657-4043-8310-7c465fd0d293
		summarizeBy: sum
		sourceColumn: Gasto com Brinquedos

		annotation SummarizationSetBy = Automatic

	column 'Gasto com Moveis'
		dataType: int64
		formatString: 0
		lineageTag: 4d7ae574-aaec-424c-a1e6-df223c11fc91
		summarizeBy: sum
		sourceColumn: Gasto com Moveis

		annotation SummarizationSetBy = Automatic

	column 'Gasto com Utilidades'
		dataType: int64
		formatString: 0
		lineageTag: c93bfb8d-54bb-47d4-a1c9-1f9c8d32724a
		summarizeBy: sum
		sourceColumn: Gasto com Utilidades

		annotation SummarizationSetBy = Automatic

	column 'Gasto com Alimentos'
		dataType: int64
		formatString: 0
		lineageTag: 4e9cad5e-d3a1-475d-8189-d757ecf409c7
		summarizeBy: sum
		sourceColumn: Gasto com Alimentos

		annotation SummarizationSetBy = Automatic

	column 'Gasto com Vestuario'
		dataType: int64
		formatString: 0
		lineageTag: 898da5b6-6660-4a08-9c1e-830b35a89ddc
		summarizeBy: sum
		sourceColumn: Gasto com Vestuario

		annotation SummarizationSetBy = Automatic

	column 'Numero de Compras com Desconto'
		dataType: int64
		formatString: 0
		lineageTag: fcfa85d0-4e5d-498d-80c7-facc1670cce0
		summarizeBy: sum
		sourceColumn: Numero de Compras com Desconto

		annotation SummarizationSetBy = Automatic

	column 'Numero de Compras na Web'
		dataType: int64
		formatString: 0
		lineageTag: 3f3e2895-f960-480e-a8a1-b2cf26d6432d
		summarizeBy: sum
		sourceColumn: Numero de Compras na Web

		annotation SummarizationSetBy = Automatic

	column 'Numero de Compras via Catalogo'
		dataType: int64
		formatString: 0
		lineageTag: 50b4dba0-43bc-43c5-ae43-67b0c859c4a6
		summarizeBy: sum
		sourceColumn: Numero de Compras via Catalogo

		annotation SummarizationSetBy = Automatic

	column 'Numero de Compras na Loja'
		dataType: int64
		formatString: 0
		lineageTag: 50ea1454-18f0-4f5b-a33f-3e1632356f6e
		summarizeBy: sum
		sourceColumn: Numero de Compras na Loja

		annotation SummarizationSetBy = Automatic

	column 'Numero Visitas WebSite Mes'
		dataType: int64
		formatString: 0
		lineageTag: 2c3a023a-852f-48b3-8df0-aee3c7809e98
		summarizeBy: sum
		sourceColumn: Numero Visitas WebSite Mes

		annotation SummarizationSetBy = Automatic

	column 'Compra na Campanha 1'
		dataType: int64
		formatString: 0
		lineageTag: 80176440-4185-4799-99c8-9b7792351937
		summarizeBy: sum
		sourceColumn: Compra na Campanha 1

		annotation SummarizationSetBy = Automatic

	column 'Compra na Campanha 2'
		dataType: int64
		formatString: 0
		lineageTag: d8cbfa55-1fd8-4095-aee3-3126329fd27c
		summarizeBy: sum
		sourceColumn: Compra na Campanha 2

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column 'Compra na Campanha 3'
		dataType: int64
		formatString: 0
		lineageTag: 5a0a06c8-9954-4d58-8a58-af00365bc656
		summarizeBy: sum
		sourceColumn: Compra na Campanha 3

		annotation SummarizationSetBy = Automatic

	column 'Compra na Campanha 4'
		dataType: int64
		formatString: 0
		lineageTag: 2950f822-9cb5-4c25-9864-c24df438fe68
		summarizeBy: sum
		sourceColumn: Compra na Campanha 4

		annotation SummarizationSetBy = Automatic

	column 'Compra na Campanha 5'
		dataType: int64
		formatString: 0
		lineageTag: ea3710c3-5f72-4059-82b4-a62a50932d18
		summarizeBy: sum
		sourceColumn: Compra na Campanha 5

		annotation SummarizationSetBy = Automatic

	column Comprou
		dataType: string
		lineageTag: f39167b5-af4b-4fb4-9300-67b1c47ce8f1
		summarizeBy: none
		sourceColumn: Comprou

		annotation SummarizationSetBy = Automatic

	column Pais
		dataType: string
		lineageTag: c6941f39-87f1-418a-83f5-276471201cf4
		summarizeBy: none
		sourceColumn: Pais

		annotation SummarizationSetBy = Automatic

	partition DadosMarketing-35835750-7ba6-4d8c-927b-41154298d5d9 = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\JoséArimatéadeMeloJu\Documents\Portifolio\Portifolio\Dashboards\Marketing\dados_marketing.csv"),[Delimiter=";", Columns=27, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID", Int64.Type}, {"Ano Nascimento", Int64.Type}, {"Escolaridade", type text}, {"Estado Civil", type text}, {"Salario Anual", Int64.Type}, {"Filhos em Casa", Int64.Type}, {"Adolescentes em Casa", Int64.Type}, {"Data Cadastro", type date}, {"Dias Desde Ultima Compra", Int64.Type}, {"Gasto com Eletronicos", Int64.Type}, {"Gasto com Brinquedos", Int64.Type}, {"Gasto com Moveis", Int64.Type}, {"Gasto com Utilidades", Int64.Type}, {"Gasto com Alimentos", Int64.Type}, {"Gasto com Vestuario", Int64.Type}, {"Numero de Compras com Desconto", Int64.Type}, {"Numero de Compras na Web", Int64.Type}, {"Numero de Compras via Catalogo", Int64.Type}, {"Numero de Compras na Loja", Int64.Type}, {"Numero Visitas WebSite Mes", Int64.Type}, {"Compra na Campanha 1", Int64.Type}, {"Compra na Campanha 2", Int64.Type}, {"Compra na Campanha 3", Int64.Type}, {"Compra na Campanha 4", Int64.Type}, {"Compra na Campanha 5", Int64.Type}, {"Comprou", Int64.Type}, {"Pais", type text}}),
				    #"Linhas Classificadas" = Table.Sort(#"Tipo Alterado",{{"Salario Anual", Order.Descending}}),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Linhas Classificadas",1),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Linhas Superiores Removidas",{{"Comprou", type text}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado1","1","Sim",Replacer.ReplaceText,{"Comprou"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído","0","Não",Replacer.ReplaceText,{"Comprou"})
				in
				    #"Valor Substituído1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

